language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --colors --coverage-clover=coverage.clover

after_script:
  - test "5.6" == "${TRAVIS_PHP_VERSION}" && wget https://scrutinizer-ci.com/ocular.phar
  - test -f ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
